# Generated by Django 4.2 on 2025-06-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=30)),
                ('fase', models.PositiveIntegerField()),
                ('data_prova', models.DateField(blank=True, null=True)),
                ('gabarito_oficial', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.escola')),
            ],
        ),
        migrations.CreateModel(
            name='LeituraGabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_aluno', models.JSONField(default=dict)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acertos', models.IntegerField(blank=True, null=True)),
                ('erros', models.IntegerField(blank=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.participante')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.prova')),
            ],
            options={
                'unique_together': {('participante', 'prova')},
            },
        ),
    ]
