# Generated by Django 5.2.3 on 2025-06-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='escola',
        ),
        migrations.AlterUniqueTogether(
            name='leituragabarito',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leituragabarito',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='leituragabarito',
            name='prova',
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
        migrations.DeleteModel(
            name='LeituraGabarito',
        ),
        migrations.DeleteModel(
            name='Prova',
        ),
    ]
