services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql://oci_user:oci_pass@db:3306/oci_db
      - SECRET_KEY=sua-senha-super-dificil-de-adivinhar-aqui
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: umasenhaforteparaoroot # Senha do superusuário 'root'
      MYSQL_DATABASE: oci_db          # Nome do banco de dados que será criado
      MYSQL_USER: oci_user            # Um novo usuário que será criado para a aplicação
      MYSQL_PASSWORD: oci_pass        # A senha para esse novo usuário
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"

volumes:
  mysql_data:
