# Generated by Django 5.2.3 on 2025-06-17 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(default='nenhuma', max_length=30)),
                ('fase', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'provas',
            },
        ),
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura', models.CharField(max_length=255)),
                ('erro', models.IntegerField()),
                ('aluno', models.ForeignKey(db_column='id_alunos', on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('usuario', models.ForeignKey(db_column='nome_arquivo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prova', models.ForeignKey(db_column='id_prova', on_delete=django.db.models.deletion.CASCADE, to='home.prova')),
            ],
            options={
                'db_table': 'gabaritos',
            },
        ),
    ]
