# Generated by Django 5.2.3 on 2025-06-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'provas',
            },
        ),
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura', models.CharField(max_length=255)),
                ('erro', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.prova')),
            ],
            options={
                'db_table': 'gabaritos',
            },
        ),
    ]
