# Generated by Django 5.2.3 on 2025-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='modalidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
