# Generated by Django 5.2.3 on 2025-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_prova_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='modalidade',
            field=models.CharField(default='nenhuma', max_length=30),
        ),
    ]
