# Generated by Django 5.2.3 on 2025-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_prova_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='fase',
            field=models.CharField(default='fase', max_length=30),
        ),
    ]
