# Generated by Django 5.2.3 on 2025-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_prova_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='fase',
            field=models.IntegerField(default=1),
        ),
    ]
