# Generated by Django 5.2.3 on 2025-06-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_prova_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabarito',
            name='aluno',
            field=models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='home.aluno'),
        ),
        migrations.AlterField(
            model_name='gabarito',
            name='prova',
            field=models.ForeignKey(db_column='id_prova', on_delete=django.db.models.deletion.CASCADE, to='home.prova'),
        ),
    ]
