# Generated by Django 5.2.3 on 2025-06-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gabarito_aluno_alter_gabarito_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabarito',
            name='aluno',
            field=models.ForeignKey(db_column='id_alunos', on_delete=django.db.models.deletion.CASCADE, to='home.aluno'),
        ),
        migrations.AlterField(
            model_name='gabarito',
            name='prova',
            field=models.ForeignKey(db_column='id_provas', on_delete=django.db.models.deletion.CASCADE, to='home.prova'),
        ),
    ]
