# Generated by Django 5.2.3 on 2025-06-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('home', '0008_alter_gabarito_aluno_alter_gabarito_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabarito',
            name='aluno',
            field=models.ForeignKey(db_column='id_alunos', on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='gabarito',
            name='prova',
            field=models.ForeignKey(db_column='id_prova', on_delete=django.db.models.deletion.CASCADE, to='home.prova'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
